[package]
edition = "2021"
name = "ms"
version = "0.0.1"

[dependencies]
anyhow = "1.0.86"
indexmap = "2.2.6"
itertools = "0.13.0"
nom = "7.1.3"
ordered-float = "4.2.0"
polars = { version = "0.40.0", features = ["lazy", "regex"] }
ron = "0.8.1"
serde = { version = "1.0.203", features = ["derive", "std"] }
thiserror = "1.0.61"
tracing = "0.1.40"
uom = "0.36.0"

# uom = { git = "https://github.com/iliekturtles/uom", features = ["std"] }
# nom-derive = "0.10.0"
